[package]
name = "abra_module_time"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
abra_core = { workspace = true }

[build-dependencies]
abra_core = { workspace = true }
