[package]
name = "time"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
abra_core = { path = "../../../abra_core" }

[build-dependencies]
abra_core = { path = "../../../abra_core" }
