// This is @generated by Abra build system

use abra_core::host_bindings::*;
use abra_core::vm::*;

#[allow(dead_code)]
pub enum HostFunction {
    GetArgs,
    PrintString,
    Readline,
}
impl From<u16> for HostFunction {
    fn from(item: u16) -> Self {
        match item {
            0 => HostFunction::GetArgs,
            1 => HostFunction::PrintString,
            2 => HostFunction::Readline,
            i => panic!("unrecognized host func: {i}"),
        }
    }
}
pub enum HostFunctionArgs {
    GetArgs,
    PrintString(String),
    Readline,
}
impl HostFunctionArgs {
    pub(crate) fn from_vm(vm: &mut Vm, pending_host_func: u16) -> Self {
        match pending_host_func {
            0 => HostFunctionArgs::GetArgs,
            1 => {
                let arg0: String = <String>::from_vm(vm);
                HostFunctionArgs::PrintString(arg0)
            }
            2 => HostFunctionArgs::Readline,
            _ => panic!("unexpected tag encountered: {pending_host_func}"),
        }
    }
}
pub enum HostFunctionRet {
    GetArgs(Vec<String>),
    PrintString,
    Readline(String),
}
impl HostFunctionRet {
    pub(crate) fn into_vm(self, vm: &mut Vm) {
        match self {
            HostFunctionRet::GetArgs(out) => {
                out.to_vm(vm);
            }
            HostFunctionRet::PrintString => {}
            HostFunctionRet::Readline(out) => {
                out.to_vm(vm);
            }
        }
        vm.clear_pending_host_func()
    }
}
