[package]
name = "random"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
abra_core = { path = "../../../crates/core" }
rand = "0.9.0"

[build-dependencies]
abra_core = { path = "../../../crates/core" }
