[package]
name = "abra_module_random"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]
test = false
[dependencies]
abra_core = { workspace = true }
rand = "0.9.1"

[build-dependencies]
abra_core = { workspace = true }
