// This is @generated by Abra build system

mod time;
pub mod ffi {
    pub mod time {
        use crate::time;
        use abra_core::addons::*;
        #[allow(unused)]
        use abra_core::vm::AbraInt;
        use std::ffi::c_void;
        /// # Safety
        /// `vm` must be non-null and valid.
        #[unsafe(export_name = "abra_ffi$time$get_time")]
        pub unsafe extern "C" fn get_time(_vm: *mut c_void, vm_funcs: *const AbraVmFunctions) {
            unsafe {
                let _vm_funcs: &AbraVmFunctions = &*vm_funcs;
                let ret: f64 = time::get_time();
                ret.to_vm_unsafe(_vm, _vm_funcs);
            }
        }
        /// # Safety
        /// `vm` must be non-null and valid.
        #[unsafe(export_name = "abra_ffi$time$sleep")]
        pub unsafe extern "C" fn sleep(_vm: *mut c_void, vm_funcs: *const AbraVmFunctions) {
            unsafe {
                let _vm_funcs: &AbraVmFunctions = &*vm_funcs;
                let seconds = <f64>::from_vm_unsafe(_vm, _vm_funcs);
                time::sleep(seconds);
            }
        }
    }
}
