#!/bin/bash

find . -path "./vendor" -prune -o \( -name "*.rs" -o -name "*.abra" \) -print | while read filename; do echo "--- FILE: $filename ---"; cat "$filename"; echo -e "\n"; done > full_source.txt
