#!/bin/bash

set -euo pipefail

# Only build the CLI (and core), not native modules
cargo build -p abra_cli
# Run debug build of abra cli
cargo run --bin  abra -- --standard-modules modules --dynamic-libraries target/debug "$@"

