#!/bin/bash

set -euo pipefail

export DEBUG_LOG=1
export RUSTFLAGS="-A warnings"

# Build everything in the project, including native modules
cargo build --quiet
# Run debug build of abra cli
cargo run --quiet --bin  abra -- --standard-modules modules "$@"

