#!/bin/bash

set -euo pipefail

pushd core > /dev/null
cargo build
popd > /dev/null

for dir in modules/*; do
  if [ -d "$dir" ] && [ -f "$dir/rust_project/Cargo.toml" ]; then
    printf "  - building $dir ... "
    pushd "$dir/rust_project" > /dev/null
    cargo build
    popd > /dev/null
  fi
done

cargo run --bin  abra -- -m modules -s target/debug "$@"
