#!/bin/bash
set -eou pipefail

if [[ -n "${ABRA_REPOSITORY_ROOT-}" ]]; then
  export WD="$ABRA_REPOSITORY_ROOT"
else
  export WD="$PWD"
fi

cargo fmt
cargo clippy

cargo test "$@"

pushd $WD/abra_core > /dev/null
cargo check --lib --target wasm32-unknown-unknown
popd > /dev/null

cargo deny check

mdbook build book

GREEN='\033[0;32m'
NC='\033[0m' # No Color
printf "${GREEN}PASSED${NC}\n"

