#!/bin/bash
set -eou pipefail

if [[ -n "${ABRA_REPOSITORY_ROOT-}" ]]; then
  export WD="$ABRA_REPOSITORY_ROOT"
else
  export WD="$PWD"
fi

cargo fmt
cargo clippy

cargo test

pushd $WD/abra_core > /dev/null
cargo check --lib --target wasm32-unknown-unknown
popd > /dev/null

cargo deny check

