on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup toolchain install nightly-x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cargo install --locked cargo-udeps || true
          cargo install --locked cargo-deny || true
          cargo install mdbook
          rustup target add wasm32-unknown-unknown
          rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
          ./scripts/test
 
