on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests
        run: |
          rustup target add wasm32-unknown-unknown
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          cargo install cargo-udeps
          rustup default stable
          ./scripts/test


