on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable, nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cargo install --locked cargo-udeps || true
          cargo install --locked cargo-deny || true
          rustup target add wasm32-unknown-unknown
          ./scripts/test

 
